### ISSUE TITLE
Clarify reader prior understanding requirements for Tree Borrows

### ISSUE THREAD

**Issue by dhouck** [Vanille-N/website#14]
I am trying to learn more about Rust internals, and itʼs hard to figure out which things are still relevant either to current Rust or to other things Iʼm reading.  I am sure I want to read [your tree borrows writeup](https://perso.crans.org/vanille/treebor/), but Iʼm not sure what I need to read first.  It makes several references to Stack Borrows but based on skimming I expect it explains all the shared concepts, so I donʼt need to understand Stack Borrows before trying to understand Tree Borrows?

It would be useful if the page I linked had a paragraph explaining what the reader was and was not expected to understand already, similar to where it already links to the diff between the current and original versions.

**Comment by Vanille-N** [comment]
Thanks for your interest in TB. You are correct that the writeup is supposed to be understandable to someone who has no prior knowledge of Stacked Borrows. Any references to Stacked Borrows are intended to help people who already know Stacked Borrows quickly understand the differences, they should not be necessary for understanding the model from scratch.

It is currently the case that every reference to Stacked Borrows in the entire document is confined to clearly labeled `[Note: Stacked Borrows]` blocks to ensure that they can easily be skipped by someone unfamiliar with Stacked Borrows, but I do like your suggestion of making that explicit upfront by adding a disclaimer on the first page.

It's true that the first sentence being "Tree Borrows is a proposed alternative to Stacked Borrows" probably suggests a higher level of comparison with SB than is actually the case, I might try to reword said first sentence in addition to the disclaimer.

**Comment by dhouck** [comment]
Thanks for the clarification.  Iʼll probably read about TB over the weekend, then.

**Comment by Vanille-N** [comment]
With a note added to the header of the front page, I believe I can finally close this issue as future readers will already have the info.

Thanks again for your interest in TB.
