### ISSUE TITLE
Consider using less colors in CSS

### ISSUE THREAD

**Issue by matklad** [Vanille-N/website#2]
While the writing and presentation are brilliantly lucid, I personally find that the choice of color theme for text gets in a way of understanding. The contrast feels to low, and the sheer abundance of different colors creates a somewhat disorgonizing experience. That’s not a _huge_ problem, as it is somewhat satisfactory fixed by reader mode, but I figured this bit of feedback might still be useful :-)

**Comment by Vanille-N** [comment]
You make a good point. I'll admit that I haven't taken enough time to harmonize together
- the background and main text colors (taken from existing template)
- the syntax highlighting colors (barely edited from the `pandoc` default)
- the **[Note: _]** colors (default colors named by CSS)

I'll try something right now.

**Comment by matklad** [comment]
Looks much better now, thanks!
